### ISSUE TITLE
pom.xml files out of sync with build.gradle depndency versions

### ISSUE THREAD

**Issue by asaikali** [spring-cloud-samples/cloudfoundry-service-broker#21]
The pom.xml file version in based on spring boot 1.3 but the gradle version is based on boot 1.5.9. It might be easier to delete the pom.xml file and only keep the gradle build to make sure that the sample always work.

Also the maven wrapper is missing from the project even though it has a mvnw which seems to indicate that the wrapper is present.

**Comment by scottfrederick** [comment]
Fixed via #22
