### ISSUE TITLE
Username & Password

### ISSUE THREAD

**Issue by NadlerGalit** [spring-cloud-samples/cloudfoundry-service-broker#8]
Hi,

I pushed this broker to my private CF as an app. while I'm trying to connect it asks for user name and password. 

The message: "The server XXX requires username and password. The servers says:Spring".

There is any user & pwd in order to use it?

**Comment by scottfrederick** [comment]
If you haven't configured a password in the broker project, Spring Security will generate the password. See the [Security section in the README](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker#security) of the Spring Cloud - Cloud Foundry Service Broker project for more info.
