### ISSUE TITLE
Default Username and Password

### ISSUE THREAD

**Issue by pktippa** [spring-cloud-samples/cloudfoundry-service-broker#9]
Setting up default username and Password using application.properties.

**Comment by KumareshBabuNS** [comment]
Hi,
You can externally add the security username and password in environmental variables. Looks like,
SECURITY_USER_NAME = admin
SECURITY_USER_PASSWORD = admin
It works for me!!

**Comment by scottfrederick** [comment]
@pktippa For security purposes (even though this is a sample app), it is better not to hard-code the username and password used by the app. You can set them via environment variables as shown by @KumareshBabuNS during deployment.
